# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

mvn_deps = []

prebuilt_jar(name='FBTraceLogger-jar', binary_jar='FBTraceLogger.jar', visibility=['PUBLIC']);
prebuilt_jar(name='hadoop-hdfs-raid-jar', binary_jar='hdfs-raid-9.4.5.jar', visibility=['PUBLIC']);
prebuilt_jar(name='datainfra-hdfs-core-jar', binary_jar='datainfra-hdfs-core-6.1.68.jar', visibility=['PUBLIC']);
prebuilt_jar(name='hbase-jar', binary_jar='hbase-0.21.0-SNAPSHOT.jar', visibility=['PUBLIC'])
prebuilt_jar(name='json-simple-jar', binary_jar='json-simple-1.1.1.jar', visibility=['PUBLIC'])
prebuilt_jar(name='libfb303-jar', binary_jar='libfb303-0.9.0.jar', visibility=['PUBLIC'])
prebuilt_jar(name='libthrift-jar', binary_jar='libthrift-0.9.0.jar', visibility=['PUBLIC'])
prebuilt_jar(name='PrometheusAppLib-jar', binary_jar='PrometheusAppLib.jar', visibility=['PUBLIC'])
prebuilt_jar(name='PrometheusLib-jar', binary_jar='PrometheusLib.jar', visibility=['PUBLIC'])
prebuilt_jar(name='TitanMessaging-jar', binary_jar='TitanMessaging.jar', visibility=['PUBLIC'])

mvn_dependency(org='com.google.guava', name='guava', rev='14.0.1', sha1='69e12f4c6aeac392555f1ea86fab82b5e5e31ad4', deps = mvn_deps)

java_library(
    name='zookeeper-rt-deps',
    exported_deps = [
        ':FBTraceLogger-jar',
        ':datainfra-hdfs-core-jar',
        ':hadoop-hdfs-raid-jar',
        ':hbase-jar',
        ':json-simple-jar',
        ':libfb303-jar',
        ':libthrift-jar',
        ':PrometheusAppLib-jar',
        ':PrometheusLib-jar',
        ':TitanMessaging-jar',
    ] + mvn_deps,
    visibility = [ 'PUBLIC' ]
)
