
headers = subdir_glob([('src', '*.h')])

cxx_binary(
    name='zkfuse',
    #link_style='static',
    linker_flags=[
        '-lboost', '-lpthread', '-llog4cxx',
    ],
    compiler_flags=[
        '-D_FILE_OFFSET_BITS=64',
    ],
    headers=headers,
    header_namespace='',
    srcs=glob(['src/*.cc']),
    deps=['//src/c:zk-mt'],
    )
