
# we need listdir
with allow_unsafe_import():
    import os
    from glob import glob as py_glob

omit = ['fatjar', 'loggraph', 'rest', 'zktreeutil']
files = py_glob('src/contrib/*')
paths = [os.path.basename(i) for i in files
         if os.path.isdir(i) and \
         os.path.basename(i) not in omit]

reexport_dir(
    name='dist',
    path='src/contrib',
    out='contrib',
    owned=['fatjar', 'loggraph', 'rest', 'zktreeutil'],
    )
