# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

java_jar(
    name = 'zookeeper-fat',
    main_class = 'org.apache.zookeeper.util.FatJarMain',
    resources = glob(['conf/**']),
    resources_root = 'conf/',
    srcs = glob(['src/**/*.java']),
    deps = ['//src/java/main:zookeeper'],
    visibility = ['PUBLIC'],
)

files = ['conf', 'src', 'README.txt', 'build.xml', 'BUCK']
copies = []
for file in files:
    export_file(file)
    copies.append('cp -r $(location :{}) $OUT/'.format(file))

genrule(
    name='dist',
    out='fatjar',
    cmd='''
    # GENERATE FATJAR SRC
    mkdir $OUT
    cp $(location :zookeeper-fat) $OUT/zookeeper-{1}-fatjar.jar
    {0}
    '''.format('\n'.join(copies), VERSION),
    visibility=['PUBLIC'],
    )
